# Generated by Django 3.2.7 on 2021-09-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_profile_family_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='occupants',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
