# Generated by Django 3.2.7 on 2021-09-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_alter_neighborhood_occupants'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
