# Generated by Django 3.2.7 on 2021-09-22 20:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_meeting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Business photo'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='neighborhood image'),
        ),
    ]
